### ISSUE TITLE
Showing this Error, while deploying in VPS

### ISSUE THREAD

**Issue by Naim120** [ayushteke/torrent-to-gdrive-mirrorbot#27]
![Screenshot_2021-12-11-17-21-31-96_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/47737443/145675496-8e3d79be-1cc0-4d16-bb66-b4ea80668260.jpg)
Pls tell me what's the problem here

**Comment by ayushteke** [comment]
you edited your config file wrongly 

contact me on tg :- https://t.me/ayushteke
